# Generated by Django 3.2.8 on 2023-03-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
