# Generated by Django 3.2.8 on 2023-04-06 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20230406_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 6, 12, 30, 51, 244354, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 6, 12, 30, 51, 244354, tzinfo=utc), null=True),
        ),
    ]
